# ---
# domain: example.com
# ssl: true
# redirect-www: true
# locations:
#   "/":
#     proxy-to: http://app_api:8080
#   "/ws":
#     proxy-to: http://app_api:8080
#     websocket: true
# additional-config: |
#   location /foo/bar {
#     root /var/www;
#   }
